server:
  port: 8082
  servlet:
    context-path: /


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dlx_sjtm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 19911125
    #oracle配置
#    driverClassName: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@10.49.9.16/jnqbdb
#    username: jnqb_ywk
#    password: sundun_123

#    driverClassName: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@10.49.9.16/jnqbdb
#    username: rdp_jnqb
#    password: sundun


#    driver-class-name:  oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@10.49.9.16/jnqbdb
#    username: jnqb_ywk
#    password: sundun_123
#    initial-size: 5 # 初始化大小，最小，最大
#    max-active: 10 # 初始化大小，最小，最大
#    min-idle: 5 # 初始化大小，最小，最大
#    max-wait: 60000 # 配置获取连接等待超时的时间

#    driverClassName: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@10.49.9.16/jnqbdb
#    username: fkzt_ywk
#    password: fkzt_ywk

    #driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://10.49.126.74:3336/qbsq?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    #username: root
    #password: sundun_bsp


#    username: ssdp_sys
#    password: ssdp_sys
#    username: jnqb_zyk
#    password: sundun_123

    #SQLServer配置
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=renren_security
#    username: sa
#    password: 123456
    #PostgreSQL配置
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.10.10:5432/renren_security
#    username: postgres
#    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/


mybatis:
  mapperLocations: classpath:mapper/**/*.xml


pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql】
renren:
  database: mysql